import React, { useEffect, useMemo, useState } from 'react';
import { api } from './api.js';

const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const dateTime = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' });

function Skeleton({ className = '' }) { return <span className={`skeleton ${className}`} aria-hidden="true" />; }

function StatusBanner({ health, error, onRetry }) {
  if (error) return <div className="banner error" role="alert"><span>Não foi possível carregar os dados: {error}</span><button className="text-button" onClick={onRetry}>Tentar novamente</button></div>;
  if (health && !health.baseLinkerConfigured) return <div className="banner warning" role="status">Conexão não configurada. Defina <code>BASELINKER_TOKEN</code> no backend para exibir os dados reais.</div>;
  if (health) return <div className="banner success" role="status">Conexão BaseLinker disponível. Escrita: {health.writeEnabled ? 'habilitada' : 'bloqueada para homologação'}.</div>;
  return null;
}

function Nav({ active, onChange }) {
  const entries = [['dashboard', 'Visão geral'], ['orders', 'Pedidos'], ['queues', 'Filas'], ['inventory', 'Estoque'], ['settings', 'Configuração']];
  return <aside className="sidebar"><div className="brand"><span className="brand-mark">J</span><span>JRDEV1</span></div><nav aria-label="Navegação principal">{entries.map(([id, label]) => <button key={id} className={active === id ? 'nav-item active' : 'nav-item'} onClick={() => onChange(id)}>{label}</button>)}</nav><div className="sidebar-foot">Operação BaseLinker<br /><span>Modo seguro</span></div></aside>;
}

function Metric({ label, value, detail, loading }) { return <section className="metric"><p>{label}</p><strong>{loading ? <Skeleton /> : value}</strong><small>{detail}</small></section>; }

function OrderTable({ orders, onSelect }) {
  if (!orders.length) return <div className="empty">Nenhum pedido encontrado para este filtro.</div>;
  return <div className="table-wrap"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Fila</th><th>Pagamento</th><th>Itens</th><th></th></tr></thead><tbody>{orders.map((order) => <tr key={order.order_id}><td className="mono">#{order.order_id}</td><td>{order.delivery_fullname || order.invoice_fullname || 'Sem identificação'}</td><td className="mono">{order.order_status_id}</td><td>{money.format(Number(order.payment_done || order.total_price || 0))}</td><td>{order.products?.reduce((total, product) => total + Number(product.quantity || 0), 0) ?? 0}</td><td><button className="text-button" onClick={() => onSelect(order)}>Detalhes</button></td></tr>)}</tbody></table></div>;
}

function OrderDialog({ order, onClose }) {
  if (!order) return null;
  return <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="order-title"><header><div><p className="eyebrow">Pedido</p><h2 id="order-title" className="mono">#{order.order_id}</h2></div><button aria-label="Fechar detalhes" className="close" onClick={onClose}>×</button></header><dl className="order-meta"><div><dt>Cliente</dt><dd>{order.delivery_fullname || order.invoice_fullname || 'Não informado'}</dd></div><div><dt>Status</dt><dd className="mono">{order.order_status_id}</dd></div><div><dt>Pagamento</dt><dd>{money.format(Number(order.payment_done || order.total_price || 0))}</dd></div><div><dt>Origem</dt><dd>{order.order_source || 'Não informado'}</dd></div></dl><h3>Itens</h3><ul className="items">{(order.products || []).map((product, index) => <li key={`${product.order_product_id || product.product_id}-${index}`}><span>{product.name}</span><span className="mono">{product.sku || 'sem SKU'} × {product.quantity}</span></li>)}</ul><footer><button className="button secondary" onClick={onClose}>Fechar</button></footer></section></div>;
}

function Dashboard({ data, loading, onOrders, onSelect }) {
  const queues = data?.queues || [];
  return <><header className="page-heading"><div><p className="eyebrow">Operação</p><h1>Visão geral</h1><p>Acompanhamento da sincronização mais recente de pedidos confirmados.</p></div><button className="button secondary" onClick={onOrders}>Ver pedidos</button></header><div className="metrics"><Metric loading={loading} label="Pedidos confirmados hoje" value={data?.ordersToday ?? '—'} detail={data?.ordersLimited ? 'Resultado limitado a 100 pedidos.' : 'Conforme retorno da BaseLinker.'}/><Metric loading={loading} label="Valor recebido hoje" value={data ? money.format(data.revenueToday) : '—'} detail="Soma do pagamento informado nos pedidos."/><Metric loading={loading} label="Filas com pedidos" value={data?.queues?.length ?? '—'} detail="Com base no lote sincronizado."/></div><div className="grid-two"><section className="panel"><div className="panel-title"><div><p className="eyebrow">Fila</p><h2>Distribuição atual</h2></div><span className="caption">Lote consultado</span></div>{loading ? <Skeleton className="block" /> : queues.length ? <ul className="queue-list">{queues.map((queue) => <li key={queue.id}><span className="color-dot" style={{ background: queue.color || '#65717E' }}></span><span>{queue.name}</span><strong>{queue.count}</strong></li>)}</ul> : <div className="empty">Não há pedidos confirmados no lote consultado.</div>}</section><section className="panel"><div className="panel-title"><div><p className="eyebrow">Próxima ação</p><h2>Como usar este painel</h2></div></div><ol className="guidance"><li>Confirme se a conexão está disponível.</li><li>Abra uma fila e consulte os detalhes antes de separar.</li><li>Comandos de escrita ficam bloqueados até homologação.</li></ol></section></div><section className="panel"><div className="panel-title"><div><p className="eyebrow">Pedidos</p><h2>Pedidos mais recentes</h2></div></div>{loading ? <Skeleton className="block" /> : <OrderTable orders={data?.recentOrders || []} onSelect={onSelect} />}</section></>;
}

function Orders({ statuses, orders, loading, onRefresh, onSelect }) {
  const [statusId, setStatusId] = useState('');
  return <><header className="page-heading"><div><p className="eyebrow">Pedidos</p><h1>Central de pedidos</h1><p>Filtre por fila para revisar os pedidos confirmados na BaseLinker.</p></div><button className="button" onClick={() => onRefresh(statusId)}>Atualizar lista</button></header><section className="toolbar"><label>Fila<select value={statusId} onChange={(event) => { setStatusId(event.target.value); onRefresh(event.target.value); }}><option value="">Todas as filas</option>{statuses.map((status) => <option value={status.id} key={status.id}>{status.name}</option>)}</select></label><span className="caption">A BaseLinker retorna no máximo 100 pedidos por consulta.</span></section><section className="panel">{loading ? <Skeleton className="block" /> : <OrderTable orders={orders} onSelect={onSelect} />}</section></>;
}

function Queues({ statuses, dashboard, onOpenOrders }) { const [carts, setCarts] = useState([]); const [cartState, setCartState] = useState('idle'); const counts = new Map((dashboard?.queues || []).map((queue) => [String(queue.id), queue.count])); const loadCarts = async () => { setCartState('loading'); try { const data = await api('/api/pickpack/carts'); setCarts(data.carts); setCartState('ready'); } catch { setCartState('error'); } }; return <><header className="page-heading"><div><p className="eyebrow">Filas</p><h1>Controle de filas</h1><p>As filas refletem os status configurados na conta BaseLinker.</p></div></header><section className="panel">{statuses.length ? <div className="queue-grid">{statuses.map((status) => <button className="queue-card" key={status.id} onClick={() => onOpenOrders(String(status.id))}><span className="color-dot" style={{ background: status.color || '#65717E' }}></span><span>{status.name}</span><strong>{counts.get(String(status.id)) ?? '—'}</strong><small>Ver pedidos</small></button>)}</div> : <div className="empty">Os status aparecerão quando a conexão for configurada.</div>}</section><section className="panel"><div className="panel-title"><div><p className="eyebrow">Pick & Pack</p><h2>Carrinhos de separação</h2></div><button className="button secondary" onClick={loadCarts} disabled={cartState === 'loading'}>{cartState === 'loading' ? 'Consultando…' : 'Consultar carrinhos'}</button></div>{cartState === 'idle' && <div className="empty">Consulte os carrinhos disponíveis antes de atribuir pedidos.</div>}{cartState === 'error' && <div className="empty">Não foi possível consultar os carrinhos. Confira a conexão e tente novamente.</div>}{cartState === 'ready' && (carts.length ? <ul className="queue-list">{carts.map((cart) => <li key={cart.cart_id}><span className="color-dot" style={{ background: cart.color || '#0F766E' }}></span><span>{cart.name}</span><strong className="mono">#{cart.cart_id}</strong></li>)}</ul> : <div className="empty">Nenhum carrinho de separação configurado.</div>)}</section></>;
}

function Inventory({ inventory, products, loading, onLoadProducts }) {
  const [inventoryId, setInventoryId] = useState(''); const [search, setSearch] = useState('');
  useEffect(() => { if (!inventoryId && inventory?.inventories?.[0]) setInventoryId(String(inventory.inventories[0].inventory_id)); }, [inventory, inventoryId]);
  const load = () => inventoryId && onLoadProducts(inventoryId, search);
  return <><header className="page-heading"><div><p className="eyebrow">Estoque</p><h1>Catálogo e disponibilidade</h1><p>Consulta por catálogo BaseLinker. Atualizações permanecem desativadas.</p></div></header><section className="toolbar"><label>Catálogo<select value={inventoryId} onChange={(event) => setInventoryId(event.target.value)}><option value="">Selecione</option>{(inventory?.inventories || []).map((item) => <option key={item.inventory_id} value={item.inventory_id}>{item.name} · {item.inventory_id}</option>)}</select></label><label>Busca<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Nome do produto" /></label><button className="button" onClick={load} disabled={!inventoryId}>Consultar</button></section><section className="panel"><div className="panel-title"><div><p className="eyebrow">Depósitos</p><h2>Locais disponíveis</h2></div></div><div className="warehouses">{(inventory?.warehouses || []).map((warehouse) => <span key={`${warehouse.warehouse_type}-${warehouse.warehouse_id}`}>{warehouse.name}</span>) || <span>—</span>}</div></section><section className="panel"><div className="panel-title"><div><p className="eyebrow">Produtos</p><h2>Resultado da consulta</h2></div></div>{loading ? <Skeleton className="block" /> : products.length ? <div className="table-wrap"><table><thead><tr><th>SKU</th><th>Produto</th><th>EAN</th><th>Saldo por depósito</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td className="mono">{product.sku || '—'}</td><td>{product.name}</td><td className="mono">{product.ean || '—'}</td><td className="mono">{Object.values(product.stock || {}).join(' · ') || '—'}</td></tr>)}</tbody></table></div> : <div className="empty">Escolha um catálogo e consulte para ver produtos.</div>}</section></>;
}

function Settings({ health }) { return <><header className="page-heading"><div><p className="eyebrow">Configuração</p><h1>Estado da integração</h1><p>Configurações críticas são mantidas somente no backend.</p></div></header><section className="panel config-list"><div><span>Token BaseLinker</span><strong>{health?.baseLinkerConfigured ? 'Configurado no servidor' : 'Ausente'}</strong></div><div><span>Operações de escrita</span><strong>{health?.writeEnabled ? 'Habilitadas' : 'Bloqueadas'}</strong></div><div><span>Limite de chamadas</span><strong>Espaçadas para até 100/min</strong></div></section></>;
}

export default function App() {
  const [active, setActive] = useState('dashboard'); const [health, setHealth] = useState(); const [dashboard, setDashboard] = useState(); const [statuses, setStatuses] = useState([]); const [orders, setOrders] = useState([]); const [inventory, setInventory] = useState(); const [products, setProducts] = useState([]); const [loading, setLoading] = useState(true); const [productsLoading, setProductsLoading] = useState(false); const [error, setError] = useState(''); const [selectedOrder, setSelectedOrder] = useState(null);
  const refresh = async () => { setLoading(true); setError(''); try { const healthData = await api('/health'); setHealth(healthData); if (!healthData.baseLinkerConfigured) { setDashboard(undefined); setStatuses([]); setInventory(undefined); return; } const [dashboardData, statusData, inventoryData] = await Promise.all([api('/api/dashboard'), api('/api/statuses'), api('/api/inventory')]); setDashboard(dashboardData); setStatuses(statusData.statuses); setInventory(inventoryData); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { refresh(); }, []);
  const loadOrders = async (statusId = '') => { setActive('orders'); setLoading(true); setError(''); try { const query = statusId ? `?statusId=${encodeURIComponent(statusId)}` : ''; const data = await api(`/api/orders${query}`); setOrders(data.orders); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  const loadProducts = async (inventoryId, search) => { setProductsLoading(true); setError(''); try { const query = search ? `?search=${encodeURIComponent(search)}` : ''; const data = await api(`/api/inventory/${inventoryId}/products${query}`); setProducts(data.products); } catch (err) { setError(err.message); } finally { setProductsLoading(false); } };
  const content = useMemo(() => ({ dashboard: <Dashboard data={dashboard} loading={loading} onOrders={() => loadOrders()} onSelect={setSelectedOrder}/>, orders: <Orders statuses={statuses} orders={orders} loading={loading} onRefresh={loadOrders} onSelect={setSelectedOrder}/>, queues: <Queues statuses={statuses} dashboard={dashboard} onOpenOrders={loadOrders}/>, inventory: <Inventory inventory={inventory} products={products} loading={productsLoading} onLoadProducts={loadProducts}/>, settings: <Settings health={health}/> })[active], [active, dashboard, health, inventory, loading, orders, products, productsLoading, statuses]);
  return <div className="app-shell"><Nav active={active} onChange={setActive}/><main><div className="topbar"><span className="live-dot" /> JRDEV1 <span className="topbar-divider" /> BaseLinker</div><StatusBanner health={health} error={error} onRetry={refresh}/><div className="content">{content}</div></main><OrderDialog order={selectedOrder} onClose={() => setSelectedOrder(null)}/></div>;
}
